### ISSUE TITLE
Does not highlight "json", "jsx", ...

### ISSUE THREAD

**Issue by karland** [majisoftware/react-prism#1]
Thanks for the package. It highlights "javascript", but no "json" or "jsx" (and probably no other non-core languages, but I have not tested this).

The reason is that the

```JSX
import prism from 'prismjs'
```
only imports the standard prism.js file. However this is generated primarilly for the website, as [described in the README](https://github.com/PrismJS/prism/blame/43fcb680fa0b6c37dd8f69b67f2dc8fcaccd5af6/README.md#L14) and does not contain all the languages. 

If one wanted other non-core languages to be included, it seems one needs to generate his own `prism.js` from the [download page](http://prismjs.com/download.html), which is then not imported by your package.

Alternatively, there is a discussion that you can require language files, see [here](https://github.com/PrismJS/prism/issues/972). 

So to at least allow for "json" and "jsx" you would need to require.

```JSX
import prism from 'prismjs'
require('prismjs/components/prism-jsx');
require('prismjs/components/prism-json');
```

There is probably a more general solution. What do you think?

**Comment by stephenmathieson** [comment]
Sorry, not sure why I wasn’t watching this repo!

You’re right, you’ll have to add language support on your own (just like CSS). For example:

```js
import Prism from '@majisoftware/react-prism'
import 'prismjs/components/prism-XXX'

<Prism language="XXX">...</Prism>
```

If we were to include all languages here, this component would be unnecessary huge. 

Would a note in the README suggesting this solve your problem?

**Comment by karland** [comment]
Thanks for your reply. Well, I guess I opened this issue for clarification. A note in the README would have been helpful...
